Repository POSYDON-code/POSYDON, pull requests merged in 2025-05, with the labels that each got.

#571 Change ECSN default to Tauris+15
  bin/posydon-popsyn
  bin/posydon-run-pipeline
  bin/posydon-setup-pipeline
  docs/_source/components-overview/pop_syn/population_params.rst
  docs/_source/tutorials-examples/population-synthesis/custom_step_and_flow.ipynb
  docs/_source/tutorials-examples/population-synthesis/population_params_end.ini
  posydon/binary_evol/MESA/step_mesa.py
  posydon/binary_evol/SN/profile_collapse.py
  posydon/binary_evol/SN/step_SN.py
  posydon/binary_evol/singlestar.py
  posydon/grids/MODELS.py
  posydon/grids/SN_MODELS.py
  posydon/grids/post_processing.py
  posydon/interpolation/interpolation.py
  posydon/popsyn/population_params_default.ini
  posydon/unit_tests/grids/test_MODELS.py
  posydon/unit_tests/grids/test_post_processing.py
  posydon/visualization/interpolation.py
  posydon/visualization/plot_defaults.py
Labels: v2 feature

#525 F2 f population docs
  docs/_source/tutorials-examples/population-synthesis/10_binaries_pop_syn.ipynb
  docs/_source/tutorials-examples/population-synthesis/VHD.rst
  docs/_source/tutorials-examples/population-synthesis/bbh_analysis.ipynb
  docs/_source/tutorials-examples/population-synthesis/custom_step_and_flow.ipynb
  docs/_source/tutorials-examples/population-synthesis/evolve_single_binaries.ipynb
  docs/_source/tutorials-examples/population-synthesis/lgrb_pop_syn.ipynb
  docs/_source/tutorials-examples/population-synthesis/one_met_pop_syn.ipynb
  docs/_source/tutorials-examples/population-synthesis/pop_syn.ipynb
Labels: documentation

#543 SFH bug fix, rewrite, and basic tests
  .github/workflows/continuous_integration.yml
  posydon/popsyn/rate_calculation.py
  posydon/popsyn/star_formation_history.py
  posydon/popsyn/synthetic_population.py
  posydon/unit_tests/popsyn/test_star_formation_history.py
  posydon/unit_tests/utils/test_posydonwarning.py
  posydon/utils/posydonwarning.py
Labels: bug, enhancement

#599 Update README.md
  README.md
Labels: bug, documentation

#524 Changes in the MESA documentation
  docs/_source/tutorials-examples/MESA-grids/1_hms_hms.ipynb
  docs/_source/tutorials-examples/MESA-grids/laptop.ipynb
  docs/_source/tutorials-examples/MESA-grids/running-grids.rst
  grid_params/grid_params.ini
Labels: documentation

#574 Re-writing step-CE for improved flow and logic
  docs/_source/components-overview/pop_syn/population_params.rst
  docs/_source/tutorials-examples/population-synthesis/custom_step_and_flow.ipynb
  docs/_source/tutorials-examples/population-synthesis/population_params_end.ini
  posydon/binary_evol/CE/step_CEE.py
  posydon/popsyn/population_params_default.ini
  posydon/unit_tests/utils/test_common_functions.py
  posydon/utils/common_functions.py
Labels: v2 feature
