Repository POSYDON-code/POSYDON, pull requests merged in 2025-03, with the labels that each got.

#476 Split popsyn plotting into separate components for future modularity
  posydon/visualization/plot_pop.py
Labels: enhancement

#532 Use information about dominating star in infer_mass_transfer_case
  posydon/binary_evol/DT/step_detached.py
  posydon/binary_evol/SN/profile_collapse.py
  posydon/unit_tests/utils/test_common_functions.py
  posydon/utils/common_functions.py
Labels: bug

#536 Request higher sphinx version
  setup.py
Labels: bug

#535 Update MESA-grid tutorials
  bin/posydon-setup-grid
  docs/_source/tutorials-examples/MESA-grids/1_hms_hms.ipynb
  docs/_source/tutorials-examples/MESA-grids/laptop.ipynb
  docs/_source/tutorials-examples/MESA-grids/running_a_grid.ipynb
  docs/_source/tutorials-examples/MESA-grids/running_single_hms.ipynb
  grid_params/grid_params.ini
Labels: documentation, enhancement

#507 Modular data download
  bin/get-posydon-data
  docs/_source/getting-started/installation-guide.rst
  posydon/binary_evol/MESA/step_mesa.py
  posydon/binary_evol/SN/step_SN.py
  posydon/unit_tests/utils/test_data_download.py
  posydon/unit_tests/utils/test_datasets.py
  posydon/utils/data_download.py
  posydon/utils/datasets.py
Labels: enhancement

#504 Decouple ECSN treatment from SN_MODELS
  posydon/binary_evol/SN/step_SN.py
Labels: enhancement

#541 Ensure python version 3.11
  setup.py
Labels: bug

#544 clarify population_params_default.ini
  posydon/popsyn/population_params_default.ini
Labels: enhancement

#545 Add check for valid MODELS in posydon-setup-popsyn
  bin/posydon-setup-popsyn
  posydon/binary_evol/SN/step_SN.py
  posydon/grids/MODELS.py
Labels: enhancement

#529 Add total_mass_h1 and total_mass_he4
  docs/_source/components-overview/pop_syn/population_params.rst
  docs/_source/components-overview/pop_syn/single_star.rst
  docs/_source/tutorials-examples/population-synthesis/custom_step_and_flow.ipynb
  docs/_source/tutorials-examples/population-synthesis/population_params_end.ini
  posydon/binary_evol/CE/step_CEE.py
  posydon/binary_evol/DT/step_detached.py
  posydon/binary_evol/DT/step_merged.py
  posydon/binary_evol/MESA/step_mesa.py
  posydon/binary_evol/singlestar.py
  posydon/grids/io.py
  posydon/grids/psygrid.py
  posydon/interpolation/constraints.py
  posydon/interpolation/interpolation.py
  posydon/popsyn/io.py
  posydon/popsyn/population_params_default.ini
  posydon/visualization/plot1D.py
  posydon/visualization/plot_defaults.py
Labels: enhancement

#435 Add unit tests: grids
  .github/workflows/continuous_integration.yml
  bin/posydon-run-pipeline
  posydon/grids/downsampling.py
  posydon/grids/io.py
  posydon/grids/post_processing.py
  posydon/grids/psygrid.py
  posydon/grids/scrubbing.py
  posydon/grids/termination_flags.py
  posydon/tests/grids/test_psygrid.py
  posydon/unit_tests/README.md
  posydon/unit_tests/_data/POSYDON_data/Couch+2020/Sukhbold_Mzams_He_c_core.csv
  posydon/unit_tests/_data/POSYDON_data/Couch+2020/explDatsSTIR2.json
  posydon/unit_tests/_data/POSYDON_data/Patton+Sukhbold20/Kepler_M4_table.dat
  posydon/unit_tests/_data/POSYDON_data/Patton+Sukhbold20/Kepler_Mfe_table.dat
  posydon/unit_tests/_data/POSYDON_data/Patton+Sukhbold20/Kepler_Xi_table.dat
  posydon/unit_tests/_data/POSYDON_data/Patton+Sukhbold20/Kepler_mu4_table.dat
  posydon/unit_tests/_data/POSYDON_data/Sukhbold+16/results_N20_table.csv
  posydon/unit_tests/_data/POSYDON_data/Sukhbold+16/results_S19.8_table.csv
  posydon/unit_tests/_data/POSYDON_data/Sukhbold+16/results_W15_table.csv
  posydon/unit_tests/_data/POSYDON_data/Sukhbold+16/results_W18_table.csv
  posydon/unit_tests/_data/POSYDON_data/Sukhbold+16/results_W20_table.csv
  posydon/unit_tests/grids/test_MODELS.py
  posydon/unit_tests/grids/test_downsampling.py
  posydon/unit_tests/grids/test_io.py
  posydon/unit_tests/grids/test_post_processing.py
  posydon/unit_tests/grids/test_psygrid.py
  posydon/unit_tests/grids/test_scrubbing.py
  posydon/unit_tests/grids/test_termination_flags.py
  posydon/unit_tests/utils/test_common_functions.py
  posydon/unit_tests/utils/test_configfile.py
  posydon/unit_tests/utils/test_constants.py
  posydon/unit_tests/utils/test_data_download.py
  posydon/unit_tests/utils/test_datasets.py
  posydon/unit_tests/utils/test_gridutils.py
  posydon/unit_tests/utils/test_ignorereason.py
  posydon/unit_tests/utils/test_interpolators.py
  posydon/unit_tests/utils/test_limits_thresholds.py
  posydon/unit_tests/utils/test_posydonerror.py
  posydon/unit_tests/utils/test_posydonwarning.py
  posydon/utils/posydonerror.py
Labels: enhancement

#553 Add unit test for get_MODEL_NAME
  posydon/unit_tests/grids/test_MODELS.py
Labels: URGENT

#520 Mesa api doc
  docs/_source/components-overview/mesa_grids/dynamic.rst
  docs/_source/components-overview/mesa_grids/fixed.rst
  docs/_source/components-overview/mesa_grids/inifile.rst
Labels: documentation
