Repository POSYDON-code/POSYDON, pull requests merged in 2025-07, with the labels that each got.

#604 Update dataset definitions for v2 data release
  docs/_source/getting-started/prerequisites.rst
  posydon/binary_evol/MESA/step_mesa.py
  posydon/binary_evol/SN/step_SN.py
  posydon/unit_tests/utils/test_data_download.py
  posydon/unit_tests/utils/test_datasets.py
  posydon/utils/data_download.py
  posydon/utils/datasets.py
Labels: enhancement, v2 feature

#630 Prepend path before importing versioneer
  setup.py
Labels: bug

#638 doc build on POSYDON dev test
  .github/workflows/deploy-github-pages-release.yml
  docs/_source/_templates/versions.html
  docs/_source/conf.py
Labels: bug, URGENT

#645 Update continuous_integration.yml for v2.1-dev
  .github/workflows/continuous_integration.yml
Labels: enhancement, URGENT

#641 change __repr__ stepSN
  posydon/binary_evol/SN/step_SN.py
Labels: enhancement
