Repository POSYDON-code/POSYDON, pull requests merged in 2025-08, with the labels that each got.

#651 Pop params ini fix
  posydon/popsyn/population_params_default.ini
Labels: bug, URGENT

#665 installation docs: remove warnings that v2 and DR2 are not available
  docs/_source/getting-started/installation-guide.rst
Labels: documentation, v2 feature, URGENT

#671 Remove source code text from warnings
  posydon/unit_tests/utils/test_posydonwarning.py
  posydon/utils/posydonwarning.py
Labels: enhancement

#663 First steps: Validation binaries
  dev-tools/evolve_binaries.sh
  dev-tools/script_data/1Zsun_binaries_params.ini
  dev-tools/script_data/1Zsun_binaries_suite.py
Labels: enhancement

#664 [PATCH v2.0.2] Fixes to binarystar.py/binarypopulation.py for BinaryPopulation().evolve() functionality, Fix MB
  conda/meta.yaml
  posydon/binary_evol/DT/step_detached.py
  posydon/binary_evol/MESA/step_mesa.py
  posydon/binary_evol/binarystar.py
  posydon/popsyn/binarypopulation.py
  posydon/popsyn/synthetic_population.py
Labels: bug, v2 feature, URGENT
