Repository POSYDON-code/POSYDON, pull requests merged in 2025-10, with the labels that each got.

#711 [fix] no events at metallicity for model_weights
  conda/meta.yaml
  posydon/popsyn/synthetic_population.py
Labels: bug

#712 [fix] `BinaryStar.to_df()` for failed binaries
  posydon/binary_evol/binarystar.py
  posydon/popsyn/io.py
Labels: bug

#710 [feat] SHA for test binaries
  dev-tools/evolve_binaries.sh
Labels: enhancement

#718 [docs] General documentaiton changes & enhancements
  docs/_source/_static/processing_pipeline.png
  docs/_source/components-overview/pop_syn/pop_syn_debug.rst
  docs/_source/components-overview/pop_syn/population_params.rst
  docs/_source/components-overview/post_processing/pipeline.rst
  docs/_source/components-overview/post_processing/pipeline/pipeline_steps.rst
  docs/_source/components-overview/processing-pipeline.rst
  docs/_source/getting-started/installation-guide.rst
  docs/_source/index.rst
  docs/_source/tutorials-examples/MESA-grids/running-grids.rst
Labels: bug, documentation, enhancement
